apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-odoo
  namespace: databases-odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-odoo
  template:
    metadata:
      labels:
        app: postgres-odoo
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: "odoo_db"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-odoo-pvc
