apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-odoo-pvc
  namespace: databases-odoo
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
