apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-hotel-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/postgres-hotel"
