apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odoo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ton-repo-git/k8s-infra'
    targetRevision: main
    path: apps/odoo
  destination:
    server: https://kubernetes.default.svc
    namespace: odoo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
